### ISSUE TITLE
make it auto refresh

### ISSUE THREAD

**Issue by taposdas1** [auchenberg/css-reloader-chrome#14]
It is too boring to refresh by pressing f9
So make it auto refresh or coustomizeable .

**Comment by auchenberg** [comment]
Please consider using http://www.browsersync.io/ or similar instead of CSS Reloader then.

**Comment by taposdas1** [comment]
Hi there,
Please do it. I need it. I will give you for it $40

**Comment by auchenberg** [comment]
This is an open source project, not a commercial gig. 

I'd recommend you to use Browsersync or LiveReload, as they does exactly what you need.

**Comment by taposdas1** [comment]
Sir, your addons changes my life. I can earn much money by using your addons.
It keeps a web page alive . so I need it. Please help me to earn money. Please consider your little time for me a poor boy.

**Comment by taposdas1** [comment]
Please do it as a Bangladeshi brother.

**Comment by taposdas1** [comment]
Hello sir are you there?

**Comment by taposdas1** [comment]
Please do it personally for me

**Comment by lkraav** [comment]
Indeed, browsersync was the way to go for me. These addons really have no future and @auchenberg is right about suggesting you to move on.

**Comment by taposdas1** [comment]
thank you.
how can i use it?
