### ISSUE TITLE
keyIdentifier deprecation in Chrome 53

### ISSUE THREAD

**Issue by csulok** [auchenberg/css-reloader-chrome#18]
New Chrome version started showing this warning in developer tools when cssreloader is active. Not exactly sure what functionality will break when 53 lands, but it would be worth a look and updating the extension.

**[cssreloader.content.js:24](https://github.com/auchenberg/css-reloader-chrome/blob/master/cssreloader.content.js#L24)** 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

**Comment by mborn319** [comment]
[Duplicate] Duplicate of #16 .
[Fixed] Fixed by Issue #17 .
Can we mark this complete?
