### ISSUE TITLE
F9 doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by 4selin** [auchenberg/css-reloader-chrome#20]
On the settings page when I push any key I see *undefined* in keyboard shortcut field
![](https://dl.dropboxusercontent.com/1/view/8witkypmd7g74b4/Apps/Shutter/screeshot_008.png)

Ubuntu 16.04
Google Chrome 54.0.2840.59 (64-bit)

**Comment by PatrickWatzlawik** [comment]
Can confirm. Dectection of Ctrl, Shift and Alt works

**Comment by mborn319** [comment]
I believe this is probably related to #16 , which was fixed a while ago. I think the extension is outdated in the Chrome App Store, or else you would have received the update by now.
@auchenberg can you resubmit this to the Chrome store?

**Comment by auchenberg** [comment]
Version 1.1.5 has been pushed to the Chrome store. Sorry for the delay.

**Comment by 4selin** [comment]
No effect.

- removed old version from Chrome
- reboot the system
- install new version from Chrome store

Still "undefined"

**Comment by 4selin** [comment]
It works now!
Thanks a lot!

**Comment by mborn319** [comment]
Welcome @4selin ! How did you receive the update? Did you clone this repo and add to Chrome? I think we need @auchenberg to push yet another update to the Chrome store.

**Comment by PatrickWatzlawik** [comment]
I have reinstalled it from chromes webstore and had no problems anymore.
