### ISSUE TITLE
Extension gone from Chrome Store?

### ISSUE THREAD

**Issue by SinusPi** [auchenberg/css-reloader-chrome#35]
Was there a problem with the extension, seeing as it's 404 from the Chrome Web Store?

**Comment by auchenberg** [comment]
Yup, CSS Reloader is not compatible with the new Chrome APIs and store policies, so its dead.

For anyone reading this, feel free to fork this project and make it work.

**Comment by SinusPi** [comment]
FWIW, I still have it installed and it still works.
