### ISSUE TITLE
Feature idea : Cufon integration

### ISSUE THREAD

**Issue by doubouil** [auchenberg/css-reloader-chrome#5]
I love this module for bringing such a usefull function in a simple keypress. I don't use any cache while developping, and I don't have to reload pages and pages thanks to it.

The only time I have to is when I use Cufon (canvas text replacement script), which while based on CSS for styling, needs a manual refresh with JS if you change this styling.

I tried to put this line : 

if( Cufon ) {
Cufon.refresh();
}

in cssreloader.js, but nothing worked after, guess it's not that simple to edit a module.

Huge thanks even if you don't had it !

**Comment by auchenberg** [comment]
Closing as Cufon is dead. Hurray.
